# Generated by Django 4.0.4 on 2022-04-27 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Admission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('child_name', models.CharField(max_length=100)),
                ('class_join', models.IntegerField(default=1)),
                ('international_id', models.CharField(max_length=20)),
                ('october_age', models.CharField(blank=True, max_length=10)),
                ('address', models.CharField(max_length=100)),
                ('is_joined_before', models.CharField(default='NO', max_length=5)),
                ('is_joined_name', models.CharField(blank=True, max_length=100)),
                ('is_joined_duration', models.IntegerField(blank=True)),
                ('siblings_count', models.CharField(default='NO', max_length=5)),
                ('siblings_count_name', models.CharField(blank=True, max_length=100)),
                ('siblings_count_class', models.IntegerField(blank=True, default=1)),
                ('phone_number', models.CharField(max_length=12)),
                ('email', models.EmailField(max_length=254)),
                ('mother_name', models.CharField(max_length=100)),
                ('mother_phone_number', models.CharField(max_length=12)),
                ('mother_job', models.IntegerField(default=1)),
                ('what_mother_job', models.CharField(blank=True, max_length=100)),
                ('mother_qualification', models.CharField(default='DB', max_length=10)),
                ('mother_qualification_other', models.CharField(blank=True, max_length=50)),
                ('father_name', models.CharField(max_length=100)),
                ('father_job', models.CharField(max_length=50)),
                ('father_qualification', models.CharField(default='DB', max_length=10)),
                ('father_qualification_other', models.CharField(blank=True, max_length=50)),
                ('father_phone_number', models.CharField(max_length=12)),
            ],
        ),
    ]
