# Generated by Django 4.0.4 on 2022-04-27 03:02

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('admission', '0002_admission_birth_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admission',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
