# Generated by Django 4.0.4 on 2022-04-27 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admission', '0004_alter_admission_is_joined_duration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admission',
            name='mother_qualification_other',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
