# Generated by Django 4.0.4 on 2022-04-27 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admission', '0005_alter_admission_mother_qualification_other'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admission',
            name='father_qualification_other',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='admission',
            name='is_joined_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='admission',
            name='siblings_count_class',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
        migrations.AlterField(
            model_name='admission',
            name='siblings_count_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='admission',
            name='what_mother_job',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
