# Generated by Django 4.0.4 on 2022-04-27 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admission', '0006_alter_admission_father_qualification_other_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admission',
            name='father_phone_number',
            field=models.CharField(max_length=12, null=True),
        ),
    ]
