# Generated by Django 4.0.4 on 2022-04-27 21:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('admission', '0008_alter_admission_father_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admission',
            name='father_phone_number',
            field=models.CharField(max_length=12),
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notif_type', models.CharField(max_length=100, verbose_name='Notification Type')),
                ('sender', models.EmailField(blank=True, max_length=254, null=True)),
                ('read_notif', models.BooleanField(default=False, verbose_name='Notification Read')),
                ('notif_name', models.CharField(blank=True, max_length=50, null=True)),
                ('rec', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='receiver')),
            ],
        ),
    ]
