# Generated by Django 4.0.4 on 2022-05-15 10:04

import apps.gallery.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gallery',
            options={'ordering': ('-image',)},
        ),
        migrations.AlterField(
            model_name='gallery',
            name='image',
            field=models.ImageField(height_field=570, upload_to=apps.gallery.models.create_albums, width_field=440),
        ),
    ]
